@url = http://127.0.0.1:3001
@id=6a87df2a-9686-4400-88b0-af578b1859c3

//Gets

###
//Posts
POST {{url}}/solos HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nivel_ph": 6.0,
    "tipo_solo": "TIPOB",
    "prevencao": "tralala",
    "temperatura": 39.6,
    "tipo_vaso": "TIPOA"
}
###
// Puts
PUT {{url}}/solos/{{id}} HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "nivel_ph": 6.2,
    "tipo_solo": "TIPOC",
    "prevencao": "blabla",
    "temperatura": 36.2,
    "tipo_vaso": "TIPOB"
}